[package]
name = "web_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
boa_engine = { workspace = true }
env_logger = { workspace = true }
error = { path = "../error" }
log = { workspace = true }
reqwest = { workspace = true }
ron = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
