[workspace]
resolver = "3"
members = [
  "./crates/frontend",
  "./crates/raesan",
  "./crates/web_scraper",
  "./crates/schema",
  "./crates/tree_schema",
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
boa_engine = "0.21.0"
env_logger = "0.11.8"
leptos = { version = "0.8.15", default-features = false, features = ["ssr"] }
log = "0.4.29"
reqwest = { version = "0.13.1", default-features = false, features = [
  "default-tls",
] }
ron = "0.12.0"
rstest = "0.26.1"
scraper = "0.25.0"
serde = "1.0.228"
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.21.0", features = ["v4"] }

[profile.dev]
incremental = true
