[package]
name = "error"
version = { workspace = true }
edition = { workspace = true }

[features]
axum = ["dep:axum"]
tauri = ["dep:tauri"]
boa_engine = ["dep:boa_engine"]
reqwest = ["dep:reqwest"]
scraper = ["dep:scraper"]
sqlx = ["dep:sqlx"]
tokio = ["dep:tokio"]

[dependencies]
axum = { workspace = true, optional = true }
boa_engine = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
scraper = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, optional = true }
tauri = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
