[package]
name = "raesan"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true }
env_logger = { workspace = true }
error = { path = "../error", default-features = false, features = ["sqlx"] }
rand = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
rstest = { workspace = true }
schema = { path = "../schema" }
sqlx = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
